import Foundation

/// Source for the Node.js runner that drives a headful Chromium window
/// for ScreenMuse to record. Written to disk by `NodeRunnerInstaller`.
///
/// The runner speaks a minimal line-based protocol on stdout so Swift can
/// coordinate the recording lifecycle with the browser lifecycle:
///
///   SM:READY:{json}       — browser launched, window visible, ready to record
///   SM:SCRIPT_OK          — user script finished without error
///   SM:SCRIPT_ERROR:msg   — user script threw
///   SM:NAV_ERROR:msg      — page.goto failed
///   SM:DONE:{json}        — browser closed, runner exiting cleanly
///   SM:FATAL:msg          — unrecoverable error in runner itself
///
/// The runner reads "GO\n" from stdin after Swift has started recording.
/// If the GO signal never arrives, it proceeds after a 10s timeout so a
/// dead parent doesn't leave a Chromium window stranded.
enum RunnerScript {

    /// Filename for the runner script on disk. Lives in the installer's
    /// `runnerDirectory` (default: `~/.screenmuse/playwright-runner/`).
    static let filename = "runner.js"

    /// Version stamp embedded into the runner. Bump this when the protocol
    /// or script logic changes so the installer re-writes stale files.
    static let version = "1"

    /// The Node.js source. Keep this in sync with `RunnerProtocolTests`.
    static let source: String = #"""
    #!/usr/bin/env node
    // ScreenMuse browser runner (generated by NodeRunnerInstaller, version __SM_VERSION__).
    //
    // Launches a real Chromium window for the macOS-level screen capture
    // pipeline to record, then runs an optional user script in page context.
    //
    // Do not edit this file on disk — it will be overwritten by the
    // installer. Edit RunnerScript.swift in ScreenMuseCore instead.
    'use strict';

    const readline = require('readline');

    const startTs = Date.now();

    async function main() {
      const raw = process.argv[2] || '{}';
      let config;
      try {
        config = JSON.parse(raw);
      } catch (e) {
        emit('FATAL', 'invalid config JSON: ' + e.message);
        process.exit(1);
      }

      let playwright;
      try {
        playwright = require('playwright');
      } catch (e) {
        emit('FATAL', 'playwright not installed in runner directory — run POST /browser/install');
        process.exit(1);
      }

      const width = positiveInt(config.width, 1280);
      const height = positiveInt(config.height, 720);

      const browser = await playwright.chromium.launch({
        headless: false,
        args: [
          '--window-size=' + width + ',' + height,
          '--window-position=100,100',
          '--no-first-run',
          '--disable-default-apps',
          '--disable-infobars',
          '--disable-session-crashed-bubble'
        ]
      });

      const context = await browser.newContext({
        viewport: { width: width, height: height },
        deviceScaleFactor: 1
      });
      const page = await context.newPage();

      let navError = null;
      try {
        await page.goto(config.url, {
          waitUntil: 'load',
          timeout: positiveInt(config.nav_timeout_ms, 30000)
        });
      } catch (e) {
        navError = e.message;
        emit('NAV_ERROR', navError);
      }

      const title = await page.title().catch(() => config.url || 'Chromium');
      emit('READY', JSON.stringify({
        title: title,
        pid: process.pid,
        url: page.url(),
        nav_error: navError
      }));

      // Wait for Swift to signal it has started recording (GO on stdin).
      // Fall back to a short sleep if no signal arrives in 10s so we never
      // strand a visible browser window because the parent crashed.
      await waitForGo(10000);

      let scriptError = null;
      if (typeof config.script === 'string' && config.script.trim() !== '') {
        try {
          // Run the user's code as an async function with page/context/browser
          // in scope. This is inherently trusting — documented in SECURITY.md.
          // eslint-disable-next-line no-new-func
          const userFn = new Function(
            'page', 'context', 'browser',
            '"use strict"; return (async () => { ' + config.script + ' })();'
          );
          await userFn(page, context, browser);
          emit('SCRIPT_OK', '');
        } catch (e) {
          scriptError = e.message || String(e);
          emit('SCRIPT_ERROR', scriptError);
        }
      }

      // Keep the window alive for the remaining duration, so speedramp and
      // idle-detection have real frames to work with. If the script errored,
      // bail out immediately — no point recording a dead page.
      const totalMs = positiveInt(config.duration_ms, 5000);
      const elapsed = Date.now() - startTs;
      const remaining = Math.max(0, totalMs - elapsed);
      if (remaining > 0 && scriptError === null) {
        await sleep(remaining);
      }

      try { await browser.close(); } catch (e) { /* ignore close errors */ }

      emit('DONE', JSON.stringify({
        script_error: scriptError,
        nav_error: navError,
        elapsed_ms: Date.now() - startTs
      }));
      process.exit(scriptError !== null || navError !== null ? 2 : 0);
    }

    function emit(tag, payload) {
      // All runner events use this envelope so the Swift parser can skip
      // noise from Playwright/Chromium on stdout or stderr.
      process.stdout.write('SM:' + tag + ':' + payload + '\n');
    }

    function positiveInt(value, fallback) {
      const n = parseInt(value, 10);
      return Number.isFinite(n) && n > 0 ? n : fallback;
    }

    function sleep(ms) {
      return new Promise(function (resolve) { setTimeout(resolve, ms); });
    }

    function waitForGo(timeoutMs) {
      return new Promise(function (resolve) {
        const rl = readline.createInterface({ input: process.stdin });
        const timer = setTimeout(function () {
          rl.close();
          resolve();
        }, timeoutMs);
        rl.on('line', function (line) {
          if (line === 'GO') {
            clearTimeout(timer);
            rl.close();
            resolve();
          }
        });
      });
    }

    main().catch(function (e) {
      emit('FATAL', (e && e.message) || String(e));
      process.exit(1);
    });
    """#

    /// Returns the runner source with the current version stamp injected.
    static func rendered() -> String {
        return source.replacingOccurrences(of: "__SM_VERSION__", with: version)
    }

    /// Minimal package.json written alongside the runner. Pinning the
    /// Playwright version avoids silent breakage from upstream changes.
    static let packageJSON = """
    {
      "name": "screenmuse-playwright-runner",
      "version": "1.0.0",
      "private": true,
      "description": "Node.js runner that drives Chromium for the POST /browser endpoint",
      "dependencies": {
        "playwright": "1.47.0"
      }
    }
    """
}
